// DOM Element References
export const elements = {
    loginModal: document.getElementById('loginModal'),
    loginForm: document.getElementById('loginForm'),
    emailInput: document.getElementById('emailInput'),
    passwordInput: document.getElementById('passwordInput'),
    loginError: document.getElementById('loginError'),
    closeModalBtn: document.getElementById('closeModalBtn'),
    authStatus: document.getElementById('authStatus'),
    userStatus: document.getElementById('userStatus'),
    loginBtn: document.getElementById('loginBtn'),
    logoutBtn: document.getElementById('logoutBtn'),
    stockForm: document.getElementById('stockForm'),
    stockIdInput: document.getElementById('stockId'),
    tickerInput: document.getElementById('ticker'),
    sharesInput: document.getElementById('shares'),
    currentProfitInput: document.getElementById('currentProfit'),
    futureProfitInput: document.getElementById('futureProfit'),
    reasonablePEInput: document.getElementById('reasonablePE'),
    overvaluedPEInput: document.getElementById('overvaluedPE'),
    stockListDiv: document.getElementById('stockList'),
    loader: document.getElementById('loader'),
    resultOutput: document.getElementById('resultOutput'),
    calculateBtn: document.getElementById('calculateBtn'),
    clearFormBtn: document.getElementById('clearFormBtn'),
    analyzeBtn: document.getElementById('analyzeBtn'),
    aiAnalysisOutput: document.getElementById('aiAnalysisOutput'),
    suggestForecastBtn: document.getElementById('suggestForecastBtn')
};