# Netlify configuration for Value Investor Dashboard
[build]
  # Build command to run before deployment
  command = "npm install && npm run build-css"

  # Directory to publish (root directory since it's a static site)
  publish = "."

  # Node version for build environment
  environment = { NODE_VERSION = "18" }

[functions]
  # Directory containing serverless functions
  directory = "netlify/functions/"

# Header rules for better performance and security
[[headers]]
  # Apply to all files
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

    # Cache control for HTML (no cache to ensure updates)
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # Cache static assets for 1 year
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache CSS for 1 year
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache service worker for 1 day (needs to update for new versions)
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  # Cache fonts for 1 year
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects and rewrites
[[redirects]]
  # SPA fallback - serve index.html for any non-existent routes
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Environment variables (for reference - set these in Netlify dashboard)
# GEMINI_API_KEY = "your_gemini_api_key_here"